#
# References
#   https://docs.travis-ci.com/user/languages/python/
#   https://blog.travis-ci.com/2019-08-07-extensive-python-testing-on-travis-ci
#   https://github.com/fabric/fabric
#
git:
  submodules: true

notifications:
  email:
    - dh.park@alcherainc.com

language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"

before_install:
  - python --version
install:
  - pip install -r requirements.txt
  # - pip install . # we need a 'setup.py'

before_script:
  # generate a temporary key and certificate
  - if [ ${TRAVIS_OS_NAME} == "linux" ]; then
    bash ./scripts/openssl_key_gen.sh;
    bash ./scripts/openssl_cert_selfsign.sh;
    bash ./scripts/run_protoc.sh;
    fi
script:
  - pytest
