site_name: "Py3 Service Template"
site_author: dh.park@alcherainc.com
site_url: http://github.com/alcherainc/py3-service-template

repo_name: alcherainc/py3-service-template
repo_url: http://github.com/alcherainc/py3-service-template

copyright: "BSD-3"

theme:
  name: readthedocs

nav:
  - Home: home.md
